### ISSUE TITLE
Scrum Update - June 13, 2021 

### ISSUE THREAD

**Issue by austincho** [valarao/chocolate-thunder-chess#53]
t9y0b

**What Did I Work on This Past Iteration**
I worked on the frontend searchBar component and started to work on some backend tasks like creating the Position schema for mongo, and creating scripts to clean up data that we web-scraped and insert them into mongo. In addition, I reviewed some PRs that rolled in this iteration.

**What Were Any Major Issues/Challenges I Ran Into**
Some challenges I ran into were deciding how to best organize the data that we had scraped. With Chess Openings, there are a lot of similar openings that only vary slightly however these openings can be referred to with a single name. However, after discussing with the team, we were able to find a solution that made the most sense in terms of supporting the web-applications functionalities. 

**What Do You Plan to Work on This Coming Iteration**
For this coming iteration, I will look to create endpoints to mongo so that our frontend components can get the most common positions and get the positions by string matching.

**Comment by AlvinCYLo** [comment]
p8c1b

**What Did I Work on This Past Iteration**
I worked on developing and integrating a navigation bar into the dashboard in addition to starting the development of Redux integration (and the ironing ofthe details around what actions/reducers to have). I also helped out with some code reviews for PRs relating to project_2

**What Were Any Major Issues/Challenges I Ran Into**
UI-wise, the hardest piece of work throughout the weeks was adequate styling and how to keep the styling consistent with the design proposed while using Material UI. Implementing and integrating Redux was also a challenge too as it was not covered in class material

**What Do You Plan to Work on This Coming Iteration**
For this coming iteration, we will continue refining some tasks to assign to each member, and I will be looking into implementing Redux for the app and possibly continuing with UI/backend development for the different components/apis

**Comment by valarao** [comment]
u0e1b

**What Did I Work on This Past Iteration**
I worked on creating the position cards and container component, getting the data from ECO, setting up backend testing, and writing the script for generating board preview images. I also helped review PRs.

**What Were Any Major Issues/Challenges I Ran Into**
The major challenge I faced was figuring out how to generate the board preview images given a particular notation, which I resolved using a library I found.

**What Do You Plan to Work on This Coming Iteration**
I plan on standardizing our color palette, developing one of the backend endpoints for the client to fetch notations data, and implementing search pagination. Ideally, we are able to finish our minimum requirements by the end of this iteration.

**Comment by joyx9** [comment]
z8t1b

**What Did I Work on This Past Iteration**
I worked on implementing the pop up dialog when clicking on a card and displaying the information of that card as well as adding the function to copy the notation info once we have our data set up. I also helped review some PRs.

**What Were Any Major Issues/Challenges I Ran Into**
My major challenges this week were getting used to Material-UI components and styling as well as handling states with the popover dialog and ensuring the states being passed between the dialog component and card component were handled properly. 

**What Do You Plan to Work on This Coming Iteration**
I am planning to implement React Router so that our application can navigate to other pages and write up info for these other pages. I would also like to touch up on current components to ensure they work with the added functionality we will be working on this iteration.
