### ISSUE TITLE
Scrum Update - June 27, 2021

### ISSUE THREAD

**Issue by austincho** [valarao/chocolate-thunder-chess#76]
t9y0b

**What Did I Work on This Past Iteration**
This sprint I worked on creating endpoints to be able to search for positions, grab variants of a position and get the most common positions. I also worked on the front end to display the data requested from our endpoints. I also worked on fixing a bug related to the preview images not being correct.

**What Were Any Major Issues/Challenges I Ran Into**
I ran into performance issues when grabbing the variants for a position. Currently we send back the image buffer of all the variants which obviously is having a negative effect when loading and displaying the variants options.

**What Do You Plan to Work on This Coming Iteration**
For this coming iteration, I will work on creating pagination for search results, removing some duplicate variants in the database and any additional tasks that come up in our meeting.

**Comment by AlvinCYLo** [comment]
p8c1b

**What Did I Work on This Past Iteration**
This sprint I worked on configuring linting scripts for both frontend and backend, and setting up lintng status checks for github actions for CI/CD. I also implemented the footer to give credit to ECO for the different positions and helped with PR code reviews. Also doing research on user authentication for log in

**What Were Any Major Issues/Challenges I Ran Into**
While doing log in research, it was hard to figure out which alternative/implementation would be best for our app

**What Do You Plan to Work on This Coming Iteration**
For this coming iteration, we will continue refining some tasks to assign to each member, and I will be looking into fully implementing a log in page with authentication for our app. Will also take on some frontend tasks as we are starting our standard requirements and getting chess gameplay started and possibly some backend functionality as we store saved user notations

**Comment by valarao** [comment]
u0e1b

**What Did I Work on This Past Iteration**
This sprint, I connected the endpoint that gets opening data from the DB and the frontend. I also standardized the application colors with a theme provider, as well as setup GitHub Actions Testing CI/CD to ensure backend endpoints are working and the frontend builds. Lastly, I began to setup the page that allows users to play against a game.

**What Were Any Major Issues/Challenges I Ran Into**
One major challenge I had was figuring out how to convert an image data buffer into an image to display on the frontend. 

**What Do You Plan to Work on This Coming Iteration**
Next iteration, I plan to continue to implement the game page that allows you to play a game against yourself (at first).

**Comment by joyx9** [comment]
z8t1b

**What Did I Work on This Past Iteration**
I worked on setting up React Router and making placeholder pages so the application can navigate to different pages. I also made mock-ups for the game page area to get an idea of what we wanted the page to look like.

**What Were Any Major Issues/Challenges I Ran Into**
When setting up React Router, I ran into some issues trying to implement Router with the built-in material-ui components.

**What Do You Plan to Work on This Coming Iteration**
Next iteration, I plan to work on creating a favourites page so that users can bookmark their favourite positions and access them easily, and looking into collections in mongoDB to do so. I also plan to work on the information side of the game page that will hold basic information of the game being played and contains the invite link to play against other people.
